services:
  - type: web
    name: vishesh-portfolio
    env: static
    buildCommand: npm ci && npx react-scripts build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html